config:
  version-candidate: VERSION
  dependencies:
    common: [snapshot]
build:
  quality:
      dependency-analysis:
        machine: graknlabs-ubuntu-20.04
        script: |
          bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
